### ISSUE TITLE
FR: Make input focus/document focus more prominent

### ISSUE THREAD

**Issue by grymmjack** [mkrueger/icy_draw#23]
It's difficult to understand which document has input focus since all the document tabs are the same color.

This is relevant when you tile a doc to the left or right of another one.

See shot:

![image](https://github.com/mkrueger/icy_draw/assets/412263/9a9289d5-b10c-4544-a542-6d64c49f7a5c)

**Comment by mkrueger** [comment]
Opened an issue in the lib I use: 
https://github.com/rerun-io/egui_tiles/issues/27

I don't really want to add another extension to egui_tiles otherwise I would need to maintain an active fork - I already made too much changes there.

But I've another solution to it - I now add the active file to the windows title. Other multi document applications do that as well for exactly this problem. Every app has that more or less.

**Comment by mkrueger** [comment]
![grafik](https://github.com/mkrueger/icy_draw/assets/341098/e40dcf56-5c1a-4116-a065-9901bf5ffede)
